/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type TermsConditionsSection = {
  _type: "termsConditionsSection";
  title?: string;
  content?: Markdown;
};

export type Markdown = string;

export type PressCoverageSection = {
  _type: "pressCoverageSection";
  title?: string;
  pressSource?: boolean;
};

export type ContactSection = {
  _type: "contactSection";
  title?: string;
  backgroundImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  contactUsImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  column1Title?: string;
  column1Info?: boolean;
  column2Title?: string;
  column2Info?: boolean;
  column3Title?: string;
  column3Info?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ContentSection = {
  _type: "contentSection";
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  section1?: {
    title?: string;
    body?: string;
  };
  section2?: {
    title?: string;
    items?: Array<{
      title?: string;
      body?: string;
      _type: "item";
      _key: string;
    }>;
  };
  section3?: {
    title?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    body?: string;
    buttonText?: string;
    buttonLink?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    };
  };
  section4?: {
    title?: string;
    buttonText?: string;
    reviews?: Array<{
      body?: string;
      person?: string;
      _type: "review";
      _key: string;
    }>;
  };
};

export type AllProjectsSection = {
  _type: "allProjectsSection";
  headline?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h1" | "h2" | "h3" | "normal";
    listItem?: never;
    markDefs?: Array<{
      markForStyling?: boolean;
      _type: "highlight";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  projectLinkText?: string;
  projectsSource?: boolean;
};

export type ProjectsSection = {
  _type: "projectsSection";
  title?: string;
  projectsPageLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  };
  projectLinkText?: string;
  viewAllLinkText?: string;
  selectedProjects?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "project";
  }>;
};

export type HeadlineSection = {
  _type: "headlineSection";
  headline?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h1" | "h2" | "h3" | "normal";
    listItem?: never;
    markDefs?: Array<{
      markForStyling?: boolean;
      _type: "highlight";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Press = {
  _id: string;
  _type: "press";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  magazineName?: string;
  media?: {
    type?: "image" | "video";
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    video?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
      };
      media?: unknown;
      _type: "file";
    };
  };
  body?: InternationalizedArrayString;
  externalLink?: string;
};

export type InternationalizedArrayString = Array<{
  _key: string;
} & InternationalizedArrayStringValue>;

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  shortDescription?: string;
  date?: string;
  projectSummary?: InternationalizedArrayString;
  projectDescription?: InternationalizedArrayString;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  previewImages?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  galleryLayout?: Array<{
    type?: string;
    images?: Array<string>;
    _type: "galleryRow";
    _key: string;
  }>;
  showContactUsButton?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  contactInfo?: {
    headOfDesign?: {
      name?: string;
      phone?: string;
      email?: string;
    };
    generalInquiries?: {
      email?: string;
    };
  };
  socialMedia?: Array<{
    platform?: "facebook" | "instagram" | "twitter" | "linkedin" | "youtube" | "tiktok";
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
  contactUsButton?: {
    text?: InternationalizedArrayString;
    contactPages?: {
      english?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
      french?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
    };
    style?: "primary" | "secondary" | "outline";
  };
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logoDesktop?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  logoMobile?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  column1?: {
    showLanguageSwitch?: boolean;
    termsPageEN?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    };
    termsPageFR?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    };
  };
  column2?: {
    useSettingsContact?: boolean;
  };
  column3?: {
    useSettingsSocial?: boolean;
  };
};

export type Navbar = {
  _id: string;
  _type: "navbar";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  navbarStructure?: {
    brandText?: string;
    logo?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    menuItems?: {
      menuItemsEN?: Array<{
        page?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "page";
        };
        mobileImage?: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        _type: "menuItem";
        _key: string;
      }>;
      menuItemsFR?: Array<{
        page?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "page";
        };
        mobileImage?: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        _type: "menuItem";
        _key: string;
      }>;
    };
  };
};

export type Locale = {
  _id: string;
  _type: "locale";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  tag?: string;
  fallback?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "locale";
  };
  default?: boolean;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<{
  _key: string;
} & InternationalizedArrayReferenceValue>;

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  };
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  language?: string;
  components?: Array<{
    images?: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }>;
    logo?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _type: "heroSection";
    _key: string;
  } | {
    headline?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h1" | "h2" | "h3" | "normal";
      listItem?: never;
      markDefs?: Array<{
        markForStyling?: boolean;
        _type: "highlight";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "headlineSection";
    _key: string;
  } | {
    title?: string;
    projectsPageLink?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    };
    projectLinkText?: string;
    viewAllLinkText?: string;
    selectedProjects?: Array<{
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: "project";
    }>;
    _type: "projectsSection";
    _key: string;
  } | {
    headline?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h1" | "h2" | "h3" | "normal";
      listItem?: never;
      markDefs?: Array<{
        markForStyling?: boolean;
        _type: "highlight";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    projectLinkText?: string;
    projectsSource?: boolean;
    _type: "allProjectsSection";
    _key: string;
  } | {
    images?: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }>;
    section1?: {
      title?: string;
      body?: string;
    };
    section2?: {
      title?: string;
      items?: Array<{
        title?: string;
        body?: string;
        _type: "item";
        _key: string;
      }>;
    };
    section3?: {
      title?: string;
      image?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      body?: string;
      buttonText?: string;
      buttonLink?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
    };
    section4?: {
      title?: string;
      buttonText?: string;
      reviews?: Array<{
        body?: string;
        person?: string;
        _type: "review";
        _key: string;
      }>;
    };
    _type: "contentSection";
    _key: string;
  } | {
    title?: string;
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    contactUsImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    column1Title?: string;
    column1Info?: boolean;
    column2Title?: string;
    column2Info?: boolean;
    column3Title?: string;
    column3Info?: boolean;
    _type: "contactSection";
    _key: string;
  } | {
    title?: string;
    pressSource?: boolean;
    _type: "pressCoverageSection";
    _key: string;
  } | {
    title?: string;
    content?: Markdown;
    _type: "termsConditionsSection";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = TermsConditionsSection | Markdown | PressCoverageSection | ContactSection | SanityImageCrop | SanityImageHotspot | ContentSection | AllProjectsSection | ProjectsSection | HeadlineSection | Press | InternationalizedArrayString | Project | Slug | Settings | Footer | Navbar | Locale | InternationalizedArrayStringValue | MediaTag | TranslationMetadata | InternationalizedArrayReference | InternationalizedArrayReferenceValue | Page | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: app/(frontend)/[slug]/page.tsx
// Variable: PAGE_QUERY_FR
// Query: *[  _type == "page"   && name == $pageName   && language == "fr"][0]{  name,  language,  components[]{    ...,    images[]{      ...    },    logo{      ...    }  }}
export type PAGE_QUERY_FRResult = {
  name: string | null;
  language: string | null;
  components: Array<{
    headline?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h1" | "h2" | "h3" | "normal";
      listItem?: never;
      markDefs?: Array<{
        markForStyling?: boolean;
        _type: "highlight";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    projectLinkText?: string;
    projectsSource?: boolean;
    _type: "allProjectsSection";
    _key: string;
    images: null;
    logo: null;
  } | {
    title?: string;
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    contactUsImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    column1Title?: string;
    column1Info?: boolean;
    column2Title?: string;
    column2Info?: boolean;
    column3Title?: string;
    column3Info?: boolean;
    _type: "contactSection";
    _key: string;
    images: null;
    logo: null;
  } | {
    images: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }> | null;
    section1?: {
      title?: string;
      body?: string;
    };
    section2?: {
      title?: string;
      items?: Array<{
        title?: string;
        body?: string;
        _type: "item";
        _key: string;
      }>;
    };
    section3?: {
      title?: string;
      image?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      body?: string;
      buttonText?: string;
      buttonLink?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
    };
    section4?: {
      title?: string;
      buttonText?: string;
      reviews?: Array<{
        body?: string;
        person?: string;
        _type: "review";
        _key: string;
      }>;
    };
    _type: "contentSection";
    _key: string;
    logo: null;
  } | {
    headline?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h1" | "h2" | "h3" | "normal";
      listItem?: never;
      markDefs?: Array<{
        markForStyling?: boolean;
        _type: "highlight";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "headlineSection";
    _key: string;
    images: null;
    logo: null;
  } | {
    images: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }> | null;
    logo: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    _type: "heroSection";
    _key: string;
  } | {
    title?: string;
    pressSource?: boolean;
    _type: "pressCoverageSection";
    _key: string;
    images: null;
    logo: null;
  } | {
    title?: string;
    projectsPageLink?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    };
    projectLinkText?: string;
    viewAllLinkText?: string;
    selectedProjects?: Array<{
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: "project";
    }>;
    _type: "projectsSection";
    _key: string;
    images: null;
    logo: null;
  } | {
    title?: string;
    content?: Markdown;
    _type: "termsConditionsSection";
    _key: string;
    images: null;
    logo: null;
  }> | null;
} | null;

// Source: app/(frontend)/en/[slug]/page.tsx
// Variable: PAGE_QUERY_EN_SLUG
// Query: *[  _type == "page"   && name == $pageName   && language == "en"][0]{  name,  language,  components[]{    _type,    _key,    ...  }}
export type PAGE_QUERY_EN_SLUGResult = {
  name: string | null;
  language: string | null;
  components: Array<{
    _type: "allProjectsSection";
    _key: string;
    headline?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h1" | "h2" | "h3" | "normal";
      listItem?: never;
      markDefs?: Array<{
        markForStyling?: boolean;
        _type: "highlight";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    projectLinkText?: string;
    projectsSource?: boolean;
  } | {
    _type: "contactSection";
    _key: string;
    title?: string;
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    contactUsImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    column1Title?: string;
    column1Info?: boolean;
    column2Title?: string;
    column2Info?: boolean;
    column3Title?: string;
    column3Info?: boolean;
  } | {
    _type: "contentSection";
    _key: string;
    images?: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }>;
    section1?: {
      title?: string;
      body?: string;
    };
    section2?: {
      title?: string;
      items?: Array<{
        title?: string;
        body?: string;
        _type: "item";
        _key: string;
      }>;
    };
    section3?: {
      title?: string;
      image?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      body?: string;
      buttonText?: string;
      buttonLink?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
    };
    section4?: {
      title?: string;
      buttonText?: string;
      reviews?: Array<{
        body?: string;
        person?: string;
        _type: "review";
        _key: string;
      }>;
    };
  } | {
    _type: "headlineSection";
    _key: string;
    headline?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h1" | "h2" | "h3" | "normal";
      listItem?: never;
      markDefs?: Array<{
        markForStyling?: boolean;
        _type: "highlight";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  } | {
    _type: "heroSection";
    _key: string;
    images?: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }>;
    logo?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  } | {
    _type: "pressCoverageSection";
    _key: string;
    title?: string;
    pressSource?: boolean;
  } | {
    _type: "projectsSection";
    _key: string;
    title?: string;
    projectsPageLink?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    };
    projectLinkText?: string;
    viewAllLinkText?: string;
    selectedProjects?: Array<{
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: "project";
    }>;
  } | {
    _type: "termsConditionsSection";
    _key: string;
    title?: string;
    content?: Markdown;
  }> | null;
} | null;

// Source: app/(frontend)/en/page.tsx
// Variable: HOME_QUERY_EN_FRONTEND
// Query: *[  _type == "page"   && name == "Home"   && language == "en"][0]{  ...,  components[]{    ...,    "images": images[]{..., asset->},    "logo": logo{..., asset->},    "backgroundImage": backgroundImage{..., asset->},    "contactUsImage": contactUsImage{..., asset->},    "mainImage": mainImage{..., asset->},    "previewImages": previewImages[]{..., asset->},    "gallery": gallery[]{..., asset->},    "selectedProjects": selectedProjects[]-> {      _id,      _type,      name,      date,      "previewImages": previewImages[]{..., asset->}    },    "projectsPageLink": projectsPageLink->{      _id,      _type,      name,      slug    }  }}
export type HOME_QUERY_EN_FRONTENDResult = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  language?: string;
  components: Array<{
    headline?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h1" | "h2" | "h3" | "normal";
      listItem?: never;
      markDefs?: Array<{
        markForStyling?: boolean;
        _type: "highlight";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    projectLinkText?: string;
    projectsSource?: boolean;
    _type: "allProjectsSection";
    _key: string;
    images: null;
    logo: null;
    backgroundImage: null;
    contactUsImage: null;
    mainImage: null;
    previewImages: null;
    gallery: null;
    selectedProjects: null;
    projectsPageLink: null;
  } | {
    title?: string;
    backgroundImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    contactUsImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    column1Title?: string;
    column1Info?: boolean;
    column2Title?: string;
    column2Info?: boolean;
    column3Title?: string;
    column3Info?: boolean;
    _type: "contactSection";
    _key: string;
    images: null;
    logo: null;
    mainImage: null;
    previewImages: null;
    gallery: null;
    selectedProjects: null;
    projectsPageLink: null;
  } | {
    images: Array<{
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }> | null;
    section1?: {
      title?: string;
      body?: string;
    };
    section2?: {
      title?: string;
      items?: Array<{
        title?: string;
        body?: string;
        _type: "item";
        _key: string;
      }>;
    };
    section3?: {
      title?: string;
      image?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      body?: string;
      buttonText?: string;
      buttonLink?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
    };
    section4?: {
      title?: string;
      buttonText?: string;
      reviews?: Array<{
        body?: string;
        person?: string;
        _type: "review";
        _key: string;
      }>;
    };
    _type: "contentSection";
    _key: string;
    logo: null;
    backgroundImage: null;
    contactUsImage: null;
    mainImage: null;
    previewImages: null;
    gallery: null;
    selectedProjects: null;
    projectsPageLink: null;
  } | {
    headline?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h1" | "h2" | "h3" | "normal";
      listItem?: never;
      markDefs?: Array<{
        markForStyling?: boolean;
        _type: "highlight";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "headlineSection";
    _key: string;
    images: null;
    logo: null;
    backgroundImage: null;
    contactUsImage: null;
    mainImage: null;
    previewImages: null;
    gallery: null;
    selectedProjects: null;
    projectsPageLink: null;
  } | {
    images: Array<{
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }> | null;
    logo: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    _type: "heroSection";
    _key: string;
    backgroundImage: null;
    contactUsImage: null;
    mainImage: null;
    previewImages: null;
    gallery: null;
    selectedProjects: null;
    projectsPageLink: null;
  } | {
    title?: string;
    pressSource?: boolean;
    _type: "pressCoverageSection";
    _key: string;
    images: null;
    logo: null;
    backgroundImage: null;
    contactUsImage: null;
    mainImage: null;
    previewImages: null;
    gallery: null;
    selectedProjects: null;
    projectsPageLink: null;
  } | {
    title?: string;
    projectsPageLink: {
      _id: string;
      _type: "page";
      name: string | null;
      slug: Slug | null;
    } | null;
    projectLinkText?: string;
    viewAllLinkText?: string;
    selectedProjects: Array<{
      _id: string;
      _type: "project";
      name: string | null;
      date: string | null;
      previewImages: Array<{
        asset: {
          _id: string;
          _type: "sanity.imageAsset";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash?: string;
          extension?: string;
          mimeType?: string;
          size?: number;
          assetId?: string;
          uploadId?: string;
          path?: string;
          url?: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }> | null;
    }> | null;
    _type: "projectsSection";
    _key: string;
    images: null;
    logo: null;
    backgroundImage: null;
    contactUsImage: null;
    mainImage: null;
    previewImages: null;
    gallery: null;
  } | {
    title?: string;
    content?: Markdown;
    _type: "termsConditionsSection";
    _key: string;
    images: null;
    logo: null;
    backgroundImage: null;
    contactUsImage: null;
    mainImage: null;
    previewImages: null;
    gallery: null;
    selectedProjects: null;
    projectsPageLink: null;
  }> | null;
} | null;

// Source: app/(frontend)/page.tsx
// Variable: HOME_QUERY_FR
// Query: *[  _type == "page"   && name == "Home"   && language == "fr"][0]{  name,  language,  components[]{    ...,    images[]{      ...    },    logo{      ...    }  }}
export type HOME_QUERY_FRResult = {
  name: string | null;
  language: string | null;
  components: Array<{
    headline?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h1" | "h2" | "h3" | "normal";
      listItem?: never;
      markDefs?: Array<{
        markForStyling?: boolean;
        _type: "highlight";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    projectLinkText?: string;
    projectsSource?: boolean;
    _type: "allProjectsSection";
    _key: string;
    images: null;
    logo: null;
  } | {
    title?: string;
    backgroundImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    contactUsImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    column1Title?: string;
    column1Info?: boolean;
    column2Title?: string;
    column2Info?: boolean;
    column3Title?: string;
    column3Info?: boolean;
    _type: "contactSection";
    _key: string;
    images: null;
    logo: null;
  } | {
    images: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }> | null;
    section1?: {
      title?: string;
      body?: string;
    };
    section2?: {
      title?: string;
      items?: Array<{
        title?: string;
        body?: string;
        _type: "item";
        _key: string;
      }>;
    };
    section3?: {
      title?: string;
      image?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      body?: string;
      buttonText?: string;
      buttonLink?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
    };
    section4?: {
      title?: string;
      buttonText?: string;
      reviews?: Array<{
        body?: string;
        person?: string;
        _type: "review";
        _key: string;
      }>;
    };
    _type: "contentSection";
    _key: string;
    logo: null;
  } | {
    headline?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h1" | "h2" | "h3" | "normal";
      listItem?: never;
      markDefs?: Array<{
        markForStyling?: boolean;
        _type: "highlight";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "headlineSection";
    _key: string;
    images: null;
    logo: null;
  } | {
    images: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }> | null;
    logo: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    _type: "heroSection";
    _key: string;
  } | {
    title?: string;
    pressSource?: boolean;
    _type: "pressCoverageSection";
    _key: string;
    images: null;
    logo: null;
  } | {
    title?: string;
    projectsPageLink?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    };
    projectLinkText?: string;
    viewAllLinkText?: string;
    selectedProjects?: Array<{
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: "project";
    }>;
    _type: "projectsSection";
    _key: string;
    images: null;
    logo: null;
  } | {
    title?: string;
    content?: Markdown;
    _type: "termsConditionsSection";
    _key: string;
    images: null;
    logo: null;
  }> | null;
} | null;

// Source: lib/navbar.ts
// Variable: NAVBAR_QUERY
// Query: *[_type == "navbar"][0]{  navbarStructure {    brandText,    logo,    menuItems {      menuItemsEN[] {        page-> {          name,          slug,          language        },        mobileImage      },      menuItemsFR[] {        page-> {          name,          slug,          language          },        mobileImage      }    }  }}
export type NAVBAR_QUERYResult = {
  navbarStructure: {
    brandText: string | null;
    logo: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    menuItems: {
      menuItemsEN: Array<{
        page: {
          name: string | null;
          slug: Slug | null;
          language: string | null;
        } | null;
        mobileImage: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
      }> | null;
      menuItemsFR: Array<{
        page: {
          name: string | null;
          slug: Slug | null;
          language: string | null;
        } | null;
        mobileImage: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
      }> | null;
    } | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[\n  _type == \"page\" \n  && name == $pageName \n  && language == \"fr\"\n][0]{\n  name,\n  language,\n  components[]{\n    ...,\n    images[]{\n      ...\n    },\n    logo{\n      ...\n    }\n  }\n}": PAGE_QUERY_FRResult;
    "*[\n  _type == \"page\" \n  && name == $pageName \n  && language == \"en\"\n][0]{\n  name,\n  language,\n  components[]{\n    _type,\n    _key,\n    ...\n  }\n}": PAGE_QUERY_EN_SLUGResult;
    "*[\n  _type == \"page\" \n  && name == \"Home\" \n  && language == \"en\"\n][0]{\n  ...,\n  components[]{\n    ...,\n    \"images\": images[]{..., asset->},\n    \"logo\": logo{..., asset->},\n    \"backgroundImage\": backgroundImage{..., asset->},\n    \"contactUsImage\": contactUsImage{..., asset->},\n    \"mainImage\": mainImage{..., asset->},\n    \"previewImages\": previewImages[]{..., asset->},\n    \"gallery\": gallery[]{..., asset->},\n    \"selectedProjects\": selectedProjects[]-> {\n      _id,\n      _type,\n      name,\n      date,\n      \"previewImages\": previewImages[]{..., asset->}\n    },\n    \"projectsPageLink\": projectsPageLink->{\n      _id,\n      _type,\n      name,\n      slug\n    }\n  }\n}": HOME_QUERY_EN_FRONTENDResult;
    "*[\n  _type == \"page\" \n  && name == \"Home\" \n  && language == \"fr\"\n][0]{\n  name,\n  language,\n  components[]{\n    ...,\n    images[]{\n      ...\n    },\n    logo{\n      ...\n    }\n  }\n}": HOME_QUERY_FRResult;
    "*[_type == \"navbar\"][0]{\n  navbarStructure {\n    brandText,\n    logo,\n    menuItems {\n      menuItemsEN[] {\n        page-> {\n          name,\n          slug,\n          language\n        },\n        mobileImage\n      },\n      menuItemsFR[] {\n        page-> {\n          name,\n          slug,\n          language  \n        },\n        mobileImage\n      }\n    }\n  }\n}": NAVBAR_QUERYResult;
  }
}
