/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type TermsConditionsSection = {
  _type: "termsConditionsSection";
  title?: string;
  content?: Markdown;
};

export type Markdown = string;

export type PressCoverageSection = {
  _type: "pressCoverageSection";
  title?: string;
  pressSource?: boolean;
};

export type ContactSection = {
  _type: "contactSection";
  title?: string;
  backgroundImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  contactUsImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  column1Title?: string;
  column1Info?: boolean;
  column2Title?: string;
  column2Info?: boolean;
  column3Title?: string;
  column3Info?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ContentSection = {
  _type: "contentSection";
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  section1?: {
    title?: string;
    body?: string;
  };
  section2?: {
    title?: string;
    items?: Array<{
      title?: string;
      body?: string;
      _type: "item";
      _key: string;
    }>;
  };
  section3?: {
    title?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    body?: string;
    buttonText?: string;
    buttonLink?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    };
  };
  section4?: {
    title?: string;
    buttonText?: string;
    buttonLink?: string;
    reviews?: Array<{
      body?: string;
      person?: string;
      _type: "review";
      _key: string;
    }>;
  };
};

export type AllProjectsSection = {
  _type: "allProjectsSection";
  headline?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h1" | "h2" | "h3" | "normal";
    listItem?: never;
    markDefs?: Array<{
      markForStyling?: boolean;
      linkToPage?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
      _type: "highlight";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  projectLinkText?: string;
  projectsPageLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  };
  projectsSource?: boolean;
};

export type ProjectsSection = {
  _type: "projectsSection";
  title?: string;
  projectsPageLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  };
  projectLinkText?: string;
  viewAllLinkText?: string;
  selectedProjects?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "project";
  }>;
};

export type HeadlineSection = {
  _type: "headlineSection";
  headline?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h1" | "h2" | "h3" | "normal";
    listItem?: never;
    markDefs?: Array<{
      markForStyling?: boolean;
      _type: "highlight";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Press = {
  _id: string;
  _type: "press";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  magazineName?: string;
  media?: {
    type?: "image" | "video";
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    video?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
      };
      media?: unknown;
      _type: "file";
    };
  };
  body?: InternationalizedArrayString;
  externalLink?: string;
};

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  shortDescription?: string;
  date?: string;
  projectSummary?: InternationalizedArrayString;
  projectDescription?: InternationalizedArrayString;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  previewImages?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    isFeatured?: boolean;
    showOnMobile?: boolean;
    isFeaturedMobile?: boolean;
    _type: "image";
    _key: string;
  }>;
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  galleryLayout?: Array<{
    type?: string;
    images?: Array<string>;
    _type: "galleryRow";
    _key: string;
  }>;
  showContactUsButton?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  contactInfo?: {
    headOfDesign?: {
      name?: string;
      phone?: string;
      email?: string;
    };
    generalInquiries?: {
      email?: string;
    };
  };
  socialMedia?: Array<{
    platform?: "Facebook" | "Instagram" | "Twitter" | "Linkedin" | "Youtube" | "Tiktok";
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
  contactUsButton?: {
    text?: InternationalizedArrayString;
    contactPages?: {
      english?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
      french?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
    };
    style?: "primary" | "secondary" | "outline";
  };
  relatedProjectsTitle?: InternationalizedArrayString;
  viewAllLinkText?: InternationalizedArrayString;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logoDesktop?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  logoMobile?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  column1?: {
    showLanguageSwitch?: boolean;
    termsPageEN?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    };
    termsPageFR?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    };
  };
  column2?: {
    useSettingsContact?: boolean;
  };
  column3?: {
    useSettingsSocial?: boolean;
  };
};

export type Navbar = {
  _id: string;
  _type: "navbar";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  navbarStructure?: {
    brandText?: string;
    logo?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    logoWhite?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    menuItems?: {
      menuItemsEN?: Array<{
        page?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "page";
        };
        mobileImage?: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        _type: "menuItem";
        _key: string;
      }>;
      menuItemsFR?: Array<{
        page?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "page";
        };
        mobileImage?: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        _type: "menuItem";
        _key: string;
      }>;
    };
  };
};

export type Locale = {
  _id: string;
  _type: "locale";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  tag?: string;
  fallback?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "locale";
  };
  default?: boolean;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  };
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  language?: string;
  components?: Array<
    | {
        images?: Array<{
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          _key: string;
        }>;
        logo?: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        _type: "heroSection";
        _key: string;
      }
    | {
        headline?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "h1" | "h2" | "h3" | "normal";
          listItem?: never;
          markDefs?: Array<{
            markForStyling?: boolean;
            _type: "highlight";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        _type: "headlineSection";
        _key: string;
      }
    | {
        title?: string;
        projectsPageLink?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "page";
        };
        projectLinkText?: string;
        viewAllLinkText?: string;
        selectedProjects?: Array<{
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          _key: string;
          [internalGroqTypeReferenceTo]?: "project";
        }>;
        _type: "projectsSection";
        _key: string;
      }
    | {
        headline?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "h1" | "h2" | "h3" | "normal";
          listItem?: never;
          markDefs?: Array<{
            markForStyling?: boolean;
            linkToPage?: {
              _ref: string;
              _type: "reference";
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: "page";
            };
            _type: "highlight";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        projectLinkText?: string;
        projectsPageLink?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "page";
        };
        projectsSource?: boolean;
        _type: "allProjectsSection";
        _key: string;
      }
    | {
        images?: Array<{
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          _key: string;
        }>;
        section1?: {
          title?: string;
          body?: string;
        };
        section2?: {
          title?: string;
          items?: Array<{
            title?: string;
            body?: string;
            _type: "item";
            _key: string;
          }>;
        };
        section3?: {
          title?: string;
          image?: {
            asset?: {
              _ref: string;
              _type: "reference";
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
            };
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          };
          body?: string;
          buttonText?: string;
          buttonLink?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "page";
          };
        };
        section4?: {
          title?: string;
          buttonText?: string;
          buttonLink?: string;
          reviews?: Array<{
            body?: string;
            person?: string;
            _type: "review";
            _key: string;
          }>;
        };
        _type: "contentSection";
        _key: string;
      }
    | {
        title?: string;
        backgroundImage?: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        contactUsImage?: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        column1Title?: string;
        column1Info?: boolean;
        column2Title?: string;
        column2Info?: boolean;
        column3Title?: string;
        column3Info?: boolean;
        _type: "contactSection";
        _key: string;
      }
    | {
        title?: string;
        pressSource?: boolean;
        _type: "pressCoverageSection";
        _key: string;
      }
    | {
        title?: string;
        content?: Markdown;
        _type: "termsConditionsSection";
        _key: string;
      }
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | TermsConditionsSection
  | Markdown
  | PressCoverageSection
  | ContactSection
  | SanityImageCrop
  | SanityImageHotspot
  | ContentSection
  | AllProjectsSection
  | ProjectsSection
  | HeadlineSection
  | Press
  | InternationalizedArrayString
  | Project
  | Slug
  | Settings
  | Footer
  | Navbar
  | Locale
  | InternationalizedArrayStringValue
  | MediaTag
  | TranslationMetadata
  | InternationalizedArrayReference
  | InternationalizedArrayReferenceValue
  | Page
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: lib/footer.ts
// Variable: FOOTER_QUERY
// Query: *[_type == "footer"][0]{  logoDesktop {    asset->{      _id,      url,      metadata {        dimensions {          width,          height        }      }    },    alt  },  logoMobile {    asset->{      _id,      url,      metadata {        dimensions {          width,          height        }      }    },    alt  },  column1 {    showLanguageSwitch,    termsPageEN->{      name,      slug    },    termsPageFR->{      name,        slug    }  },  "settingsContact": *[_type == "settings"][0].contactInfo {    headOfDesign {      name,      phone,      email    },    generalInquiries {      email    }  },  "settingsSocial": *[_type == "settings"][0].socialMedia[] {    platform,    url  },}
export type FOOTER_QUERYResult = {
  logoDesktop: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
    alt: null;
  } | null;
  logoMobile: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
    alt: null;
  } | null;
  column1: {
    showLanguageSwitch: boolean | null;
    termsPageEN: {
      name: string | null;
      slug: Slug | null;
    } | null;
    termsPageFR: {
      name: string | null;
      slug: Slug | null;
    } | null;
  } | null;
  settingsContact: {
    headOfDesign: {
      name: string | null;
      phone: string | null;
      email: string | null;
    } | null;
    generalInquiries: {
      email: string | null;
    } | null;
  } | null;
  settingsSocial: Array<{
    platform: "Facebook" | "Instagram" | "Linkedin" | "Tiktok" | "Twitter" | "Youtube" | null;
    url: string | null;
  }> | null;
} | null;

// Source: lib/navbar.ts
// Variable: NAVBAR_QUERY
// Query: *[_type == "navbar"][0]{  navbarStructure {    brandText,    logo {      asset->{        _id,        url,        metadata {          dimensions {            width,            height          }        }      },      alt    },    logoWhite {      asset->{        _id,        url,        metadata {          dimensions {            width,            height          }        }      },      alt    },    menuItems {      menuItemsEN[] {        page-> {          name,          slug,          language        },        mobileImage {          asset->{            _id,            url,            metadata {              dimensions {                width,                height              }            }          },          alt        }      },      menuItemsFR[] {        page-> {          name,          slug,          language          },        mobileImage {          asset->{            _id,            url,            metadata {              dimensions {                width,                height              }            }          },          alt        }      }    }  },  "settingsSocial": *[_type == "settings"][0].socialMedia[] {    platform,    url  },  "termsPageEN": *[_type == "page" && language == "en" && name match "*Terms*" || name match "*Conditions*"][0] {    name,    slug  },  "termsPageFR": *[_type == "page" && language == "fr" && name match "*Terms*" || name match "*Conditions*"][0] {    name,    slug  },  "settingsContact": *[_type == "settings"][0].contactInfo {    headOfDesign {      name,      phone,      email    },    generalInquiries {      email    }  }}
export type NAVBAR_QUERYResult = {
  navbarStructure: {
    brandText: string | null;
    logo: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
      alt: null;
    } | null;
    logoWhite: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
      alt: null;
    } | null;
    menuItems: {
      menuItemsEN: Array<{
        page: {
          name: string | null;
          slug: Slug | null;
          language: string | null;
        } | null;
        mobileImage: {
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          alt: null;
        } | null;
      }> | null;
      menuItemsFR: Array<{
        page: {
          name: string | null;
          slug: Slug | null;
          language: string | null;
        } | null;
        mobileImage: {
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              dimensions: {
                width: number | null;
                height: number | null;
              } | null;
            } | null;
          } | null;
          alt: null;
        } | null;
      }> | null;
    } | null;
  } | null;
  settingsSocial: Array<{
    platform: "Facebook" | "Instagram" | "Linkedin" | "Tiktok" | "Twitter" | "Youtube" | null;
    url: string | null;
  }> | null;
  termsPageEN:
    | {
        name: string | null;
        slug: null;
      }
    | {
        name: string | null;
        slug: Slug | null;
      }
    | null;
  termsPageFR:
    | {
        name: string | null;
        slug: null;
      }
    | {
        name: string | null;
        slug: Slug | null;
      }
    | null;
  settingsContact: {
    headOfDesign: {
      name: string | null;
      phone: string | null;
      email: string | null;
    } | null;
    generalInquiries: {
      email: string | null;
    } | null;
  } | null;
} | null;

// Source: lib/project.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(date desc) {  _id,  name,  slug,  shortDescription,  date,  projectSummary,  projectDescription,  mainImage {    asset-> {      _id,      url,      metadata {        dimensions {          width,          height        }      }    },    alt,    hotspot,    crop  },  "previewImages": previewImages[]{    ...,     asset->,    isFeatured,    showOnMobile,    isFeaturedMobile  },  projectGallery[] {    asset-> {      _id,      url,      metadata {        dimensions {          width,          height        }      }    },    alt,    hotspot,    crop,    showInGrid,    gridSpan  }}
export type PROJECTS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  shortDescription: string | null;
  date: string | null;
  projectSummary: InternationalizedArrayString | null;
  projectDescription: InternationalizedArrayString | null;
  mainImage: {
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
      } | null;
    } | null;
    alt: null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  previewImages: Array<{
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    isFeatured: boolean | null;
    showOnMobile: boolean | null;
    isFeaturedMobile: boolean | null;
    _type: "image";
    _key: string;
  }> | null;
  projectGallery: null;
}>;

// Source: lib/queries/home.ts
// Variable: HOME_QUERY_FR
// Query: *[  _type == "page"   && name == "Home"   && language == "fr"][0]{  ...,  components[]{    ...,    "images": images[]{..., asset->},    "logo": logo{..., asset->},    "backgroundImage": backgroundImage{..., asset->},    "contactUsImage": contactUsImage{..., asset->},    "mainImage": mainImage{..., asset->},    "previewImages": previewImages[]{..., asset->},    "gallery": gallery[]{..., asset->},    "selectedProjects": selectedProjects[]-> {      _id,      _type,      name,      slug,      date,      "previewImages": previewImages[]{        ...,         asset->,        isFeatured,        showOnMobile,        isFeaturedMobile      },    },    "projectsPageLink": projectsPageLink->{      _id,      _type,      name,      slug    },    headline[]{      ...,      markDefs[]{        ...,        "linkToPage": linkToPage->{          _id,          _type,          name,          slug        }      }    }  }}
export type HOME_QUERY_FRResult = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  language?: string;
  components: Array<
    | {
        headline: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "h1" | "h2" | "h3" | "normal";
          listItem?: never;
          markDefs: Array<{
            markForStyling?: boolean;
            linkToPage: {
              _id: string;
              _type: "page";
              name: string | null;
              slug: Slug | null;
            } | null;
            _type: "highlight";
            _key: string;
          }> | null;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        projectLinkText?: string;
        projectsPageLink: {
          _id: string;
          _type: "page";
          name: string | null;
          slug: Slug | null;
        } | null;
        projectsSource?: boolean;
        _type: "allProjectsSection";
        _key: string;
        images: null;
        logo: null;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
      }
    | {
        title?: string;
        backgroundImage: {
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        contactUsImage: {
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        column1Title?: string;
        column1Info?: boolean;
        column2Title?: string;
        column2Info?: boolean;
        column3Title?: string;
        column3Info?: boolean;
        _type: "contactSection";
        _key: string;
        images: null;
        logo: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
        projectsPageLink: null;
        headline: null;
      }
    | {
        images: Array<{
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          _key: string;
        }> | null;
        section1?: {
          title?: string;
          body?: string;
        };
        section2?: {
          title?: string;
          items?: Array<{
            title?: string;
            body?: string;
            _type: "item";
            _key: string;
          }>;
        };
        section3?: {
          title?: string;
          image?: {
            asset?: {
              _ref: string;
              _type: "reference";
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
            };
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          };
          body?: string;
          buttonText?: string;
          buttonLink?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "page";
          };
        };
        section4?: {
          title?: string;
          buttonText?: string;
          buttonLink?: string;
          reviews?: Array<{
            body?: string;
            person?: string;
            _type: "review";
            _key: string;
          }>;
        };
        _type: "contentSection";
        _key: string;
        logo: null;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
        projectsPageLink: null;
        headline: null;
      }
    | {
        headline: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "h1" | "h2" | "h3" | "normal";
          listItem?: never;
          markDefs: Array<{
            markForStyling?: boolean;
            _type: "highlight";
            _key: string;
            linkToPage: null;
          }> | null;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        _type: "headlineSection";
        _key: string;
        images: null;
        logo: null;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
        projectsPageLink: null;
      }
    | {
        images: Array<{
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          _key: string;
        }> | null;
        logo: {
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        _type: "heroSection";
        _key: string;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
        projectsPageLink: null;
        headline: null;
      }
    | {
        title?: string;
        pressSource?: boolean;
        _type: "pressCoverageSection";
        _key: string;
        images: null;
        logo: null;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
        projectsPageLink: null;
        headline: null;
      }
    | {
        title?: string;
        projectsPageLink: {
          _id: string;
          _type: "page";
          name: string | null;
          slug: Slug | null;
        } | null;
        projectLinkText?: string;
        viewAllLinkText?: string;
        selectedProjects: Array<{
          _id: string;
          _type: "project";
          name: string | null;
          slug: Slug | null;
          date: string | null;
          previewImages: Array<{
            asset: {
              _id: string;
              _type: "sanity.imageAsset";
              _createdAt: string;
              _updatedAt: string;
              _rev: string;
              originalFilename?: string;
              label?: string;
              title?: string;
              description?: string;
              altText?: string;
              sha1hash?: string;
              extension?: string;
              mimeType?: string;
              size?: number;
              assetId?: string;
              uploadId?: string;
              path?: string;
              url?: string;
              metadata?: SanityImageMetadata;
              source?: SanityAssetSourceData;
            } | null;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            isFeatured: boolean | null;
            showOnMobile: boolean | null;
            isFeaturedMobile: boolean | null;
            _type: "image";
            _key: string;
          }> | null;
        }> | null;
        _type: "projectsSection";
        _key: string;
        images: null;
        logo: null;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        headline: null;
      }
    | {
        title?: string;
        content?: Markdown;
        _type: "termsConditionsSection";
        _key: string;
        images: null;
        logo: null;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
        projectsPageLink: null;
        headline: null;
      }
  > | null;
} | null;
// Variable: HOME_QUERY_EN
// Query: *[  _type == "page"   && name == "Home"   && language == "en"][0]{  ...,  components[]{    ...,    "images": images[]{..., asset->},    "logo": logo{..., asset->},    "backgroundImage": backgroundImage{..., asset->},    "contactUsImage": contactUsImage{..., asset->},    "mainImage": mainImage{..., asset->},    "previewImages": previewImages[]{..., asset->},    "gallery": gallery[]{..., asset->},    "selectedProjects": selectedProjects[]-> {      _id,      _type,      name,      slug,      date,      "previewImages": previewImages[]{        ...,         asset->,        isFeatured,        showOnMobile,        isFeaturedMobile      },    },    "projectsPageLink": projectsPageLink->{      _id,      _type,      name,      slug    },    headline[]{      ...,      markDefs[]{        ...,        "linkToPage": linkToPage->{          _id,          _type,          name,          slug        }      }    }  }}
export type HOME_QUERY_ENResult = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  language?: string;
  components: Array<
    | {
        headline: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "h1" | "h2" | "h3" | "normal";
          listItem?: never;
          markDefs: Array<{
            markForStyling?: boolean;
            linkToPage: {
              _id: string;
              _type: "page";
              name: string | null;
              slug: Slug | null;
            } | null;
            _type: "highlight";
            _key: string;
          }> | null;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        projectLinkText?: string;
        projectsPageLink: {
          _id: string;
          _type: "page";
          name: string | null;
          slug: Slug | null;
        } | null;
        projectsSource?: boolean;
        _type: "allProjectsSection";
        _key: string;
        images: null;
        logo: null;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
      }
    | {
        title?: string;
        backgroundImage: {
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        contactUsImage: {
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        column1Title?: string;
        column1Info?: boolean;
        column2Title?: string;
        column2Info?: boolean;
        column3Title?: string;
        column3Info?: boolean;
        _type: "contactSection";
        _key: string;
        images: null;
        logo: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
        projectsPageLink: null;
        headline: null;
      }
    | {
        images: Array<{
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          _key: string;
        }> | null;
        section1?: {
          title?: string;
          body?: string;
        };
        section2?: {
          title?: string;
          items?: Array<{
            title?: string;
            body?: string;
            _type: "item";
            _key: string;
          }>;
        };
        section3?: {
          title?: string;
          image?: {
            asset?: {
              _ref: string;
              _type: "reference";
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
            };
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          };
          body?: string;
          buttonText?: string;
          buttonLink?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "page";
          };
        };
        section4?: {
          title?: string;
          buttonText?: string;
          buttonLink?: string;
          reviews?: Array<{
            body?: string;
            person?: string;
            _type: "review";
            _key: string;
          }>;
        };
        _type: "contentSection";
        _key: string;
        logo: null;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
        projectsPageLink: null;
        headline: null;
      }
    | {
        headline: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "h1" | "h2" | "h3" | "normal";
          listItem?: never;
          markDefs: Array<{
            markForStyling?: boolean;
            _type: "highlight";
            _key: string;
            linkToPage: null;
          }> | null;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        _type: "headlineSection";
        _key: string;
        images: null;
        logo: null;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
        projectsPageLink: null;
      }
    | {
        images: Array<{
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          _key: string;
        }> | null;
        logo: {
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        _type: "heroSection";
        _key: string;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
        projectsPageLink: null;
        headline: null;
      }
    | {
        title?: string;
        pressSource?: boolean;
        _type: "pressCoverageSection";
        _key: string;
        images: null;
        logo: null;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
        projectsPageLink: null;
        headline: null;
      }
    | {
        title?: string;
        projectsPageLink: {
          _id: string;
          _type: "page";
          name: string | null;
          slug: Slug | null;
        } | null;
        projectLinkText?: string;
        viewAllLinkText?: string;
        selectedProjects: Array<{
          _id: string;
          _type: "project";
          name: string | null;
          slug: Slug | null;
          date: string | null;
          previewImages: Array<{
            asset: {
              _id: string;
              _type: "sanity.imageAsset";
              _createdAt: string;
              _updatedAt: string;
              _rev: string;
              originalFilename?: string;
              label?: string;
              title?: string;
              description?: string;
              altText?: string;
              sha1hash?: string;
              extension?: string;
              mimeType?: string;
              size?: number;
              assetId?: string;
              uploadId?: string;
              path?: string;
              url?: string;
              metadata?: SanityImageMetadata;
              source?: SanityAssetSourceData;
            } | null;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            isFeatured: boolean | null;
            showOnMobile: boolean | null;
            isFeaturedMobile: boolean | null;
            _type: "image";
            _key: string;
          }> | null;
        }> | null;
        _type: "projectsSection";
        _key: string;
        images: null;
        logo: null;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        headline: null;
      }
    | {
        title?: string;
        content?: Markdown;
        _type: "termsConditionsSection";
        _key: string;
        images: null;
        logo: null;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
        projectsPageLink: null;
        headline: null;
      }
  > | null;
} | null;

// Source: lib/queries/page.ts
// Variable: PAGE_QUERY_FR
// Query: *[  _type == "page"   && slug.current == $slug   && language == "fr"][0]{  name,  language,  components[]{    ...,    "images": images[]{..., asset->},    "logo": logo{..., asset->},    "backgroundImage": backgroundImage{..., asset->},    "contactUsImage": contactUsImage{..., asset->},    "mainImage": mainImage{..., asset->},    "previewImages": previewImages[]{..., asset->},    "gallery": gallery[]{..., asset->},    "selectedProjects": selectedProjects[]-> {      _id,      _type,      name,      slug,      date,      "previewImages": previewImages[]{        ...,         asset->,        isFeatured,        showOnMobile,        isFeaturedMobile      },    },    "projectsPageLink": projectsPageLink->{      _id,      _type,      name,      slug    },    _type == "contentSection" => {      section3 {        ...,        "image": image{..., asset->},        "buttonLink": buttonLink->{          _id,          _type,          name,          slug        }      }    },    headline[]{      ...,      markDefs[]{        ...,        "linkToPage": linkToPage->{          _id,          _type,          name,          slug        }      }    }  }}
export type PAGE_QUERY_FRResult = {
  name: string | null;
  language: string | null;
  components: Array<
    | {
        headline: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "h1" | "h2" | "h3" | "normal";
          listItem?: never;
          markDefs: Array<{
            markForStyling?: boolean;
            linkToPage: {
              _id: string;
              _type: "page";
              name: string | null;
              slug: Slug | null;
            } | null;
            _type: "highlight";
            _key: string;
          }> | null;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        projectLinkText?: string;
        projectsPageLink: {
          _id: string;
          _type: "page";
          name: string | null;
          slug: Slug | null;
        } | null;
        projectsSource?: boolean;
        _type: "allProjectsSection";
        _key: string;
        images: null;
        logo: null;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
      }
    | {
        title?: string;
        backgroundImage: {
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        contactUsImage: {
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        column1Title?: string;
        column1Info?: boolean;
        column2Title?: string;
        column2Info?: boolean;
        column3Title?: string;
        column3Info?: boolean;
        _type: "contactSection";
        _key: string;
        images: null;
        logo: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
        projectsPageLink: null;
        headline: null;
      }
    | {
        images: Array<{
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          _key: string;
        }> | null;
        section1?: {
          title?: string;
          body?: string;
        };
        section2?: {
          title?: string;
          items?: Array<{
            title?: string;
            body?: string;
            _type: "item";
            _key: string;
          }>;
        };
        section3: {
          title?: string;
          image: {
            asset: {
              _id: string;
              _type: "sanity.imageAsset";
              _createdAt: string;
              _updatedAt: string;
              _rev: string;
              originalFilename?: string;
              label?: string;
              title?: string;
              description?: string;
              altText?: string;
              sha1hash?: string;
              extension?: string;
              mimeType?: string;
              size?: number;
              assetId?: string;
              uploadId?: string;
              path?: string;
              url?: string;
              metadata?: SanityImageMetadata;
              source?: SanityAssetSourceData;
            } | null;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          } | null;
          body?: string;
          buttonText?: string;
          buttonLink: {
            _id: string;
            _type: "page";
            name: string | null;
            slug: Slug | null;
          } | null;
        } | null;
        section4?: {
          title?: string;
          buttonText?: string;
          buttonLink?: string;
          reviews?: Array<{
            body?: string;
            person?: string;
            _type: "review";
            _key: string;
          }>;
        };
        _type: "contentSection";
        _key: string;
        logo: null;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
        projectsPageLink: null;
        headline: null;
      }
    | {
        headline: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "h1" | "h2" | "h3" | "normal";
          listItem?: never;
          markDefs: Array<{
            markForStyling?: boolean;
            _type: "highlight";
            _key: string;
            linkToPage: null;
          }> | null;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        _type: "headlineSection";
        _key: string;
        images: null;
        logo: null;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
        projectsPageLink: null;
      }
    | {
        images: Array<{
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          _key: string;
        }> | null;
        logo: {
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        _type: "heroSection";
        _key: string;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
        projectsPageLink: null;
        headline: null;
      }
    | {
        title?: string;
        pressSource?: boolean;
        _type: "pressCoverageSection";
        _key: string;
        images: null;
        logo: null;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
        projectsPageLink: null;
        headline: null;
      }
    | {
        title?: string;
        projectsPageLink: {
          _id: string;
          _type: "page";
          name: string | null;
          slug: Slug | null;
        } | null;
        projectLinkText?: string;
        viewAllLinkText?: string;
        selectedProjects: Array<{
          _id: string;
          _type: "project";
          name: string | null;
          slug: Slug | null;
          date: string | null;
          previewImages: Array<{
            asset: {
              _id: string;
              _type: "sanity.imageAsset";
              _createdAt: string;
              _updatedAt: string;
              _rev: string;
              originalFilename?: string;
              label?: string;
              title?: string;
              description?: string;
              altText?: string;
              sha1hash?: string;
              extension?: string;
              mimeType?: string;
              size?: number;
              assetId?: string;
              uploadId?: string;
              path?: string;
              url?: string;
              metadata?: SanityImageMetadata;
              source?: SanityAssetSourceData;
            } | null;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            isFeatured: boolean | null;
            showOnMobile: boolean | null;
            isFeaturedMobile: boolean | null;
            _type: "image";
            _key: string;
          }> | null;
        }> | null;
        _type: "projectsSection";
        _key: string;
        images: null;
        logo: null;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        headline: null;
      }
    | {
        title?: string;
        content?: Markdown;
        _type: "termsConditionsSection";
        _key: string;
        images: null;
        logo: null;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
        projectsPageLink: null;
        headline: null;
      }
  > | null;
} | null;
// Variable: PAGE_QUERY_EN
// Query: *[  _type == "page"   && slug.current == $slug   && language == "en"][0]{  name,  language,  components[]{    ...,    "images": images[]{..., asset->},    "logo": logo{..., asset->},    "backgroundImage": backgroundImage{..., asset->},    "contactUsImage": contactUsImage{..., asset->},    "mainImage": mainImage{..., asset->},    "previewImages": previewImages[]{..., asset->},    "gallery": gallery[]{..., asset->},    "selectedProjects": selectedProjects[]-> {      _id,      _type,      name,      slug,      date,      "previewImages": previewImages[]{        ...,         asset->,        isFeatured,        showOnMobile,        isFeaturedMobile      },    },    "projectsPageLink": projectsPageLink->{      _id,      _type,      name,      slug    },    _type == "contentSection" => {      section3 {        ...,        "image": image{..., asset->},        "buttonLink": buttonLink->{          _id,          _type,          name,          slug        }      }    },    headline[]{      ...,      markDefs[]{        ...,        "linkToPage": linkToPage->{          _id,          _type,          name,          slug        }      }    }  }}
export type PAGE_QUERY_ENResult = {
  name: string | null;
  language: string | null;
  components: Array<
    | {
        headline: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "h1" | "h2" | "h3" | "normal";
          listItem?: never;
          markDefs: Array<{
            markForStyling?: boolean;
            linkToPage: {
              _id: string;
              _type: "page";
              name: string | null;
              slug: Slug | null;
            } | null;
            _type: "highlight";
            _key: string;
          }> | null;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        projectLinkText?: string;
        projectsPageLink: {
          _id: string;
          _type: "page";
          name: string | null;
          slug: Slug | null;
        } | null;
        projectsSource?: boolean;
        _type: "allProjectsSection";
        _key: string;
        images: null;
        logo: null;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
      }
    | {
        title?: string;
        backgroundImage: {
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        contactUsImage: {
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        column1Title?: string;
        column1Info?: boolean;
        column2Title?: string;
        column2Info?: boolean;
        column3Title?: string;
        column3Info?: boolean;
        _type: "contactSection";
        _key: string;
        images: null;
        logo: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
        projectsPageLink: null;
        headline: null;
      }
    | {
        images: Array<{
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          _key: string;
        }> | null;
        section1?: {
          title?: string;
          body?: string;
        };
        section2?: {
          title?: string;
          items?: Array<{
            title?: string;
            body?: string;
            _type: "item";
            _key: string;
          }>;
        };
        section3: {
          title?: string;
          image: {
            asset: {
              _id: string;
              _type: "sanity.imageAsset";
              _createdAt: string;
              _updatedAt: string;
              _rev: string;
              originalFilename?: string;
              label?: string;
              title?: string;
              description?: string;
              altText?: string;
              sha1hash?: string;
              extension?: string;
              mimeType?: string;
              size?: number;
              assetId?: string;
              uploadId?: string;
              path?: string;
              url?: string;
              metadata?: SanityImageMetadata;
              source?: SanityAssetSourceData;
            } | null;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          } | null;
          body?: string;
          buttonText?: string;
          buttonLink: {
            _id: string;
            _type: "page";
            name: string | null;
            slug: Slug | null;
          } | null;
        } | null;
        section4?: {
          title?: string;
          buttonText?: string;
          buttonLink?: string;
          reviews?: Array<{
            body?: string;
            person?: string;
            _type: "review";
            _key: string;
          }>;
        };
        _type: "contentSection";
        _key: string;
        logo: null;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
        projectsPageLink: null;
        headline: null;
      }
    | {
        headline: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "h1" | "h2" | "h3" | "normal";
          listItem?: never;
          markDefs: Array<{
            markForStyling?: boolean;
            _type: "highlight";
            _key: string;
            linkToPage: null;
          }> | null;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
        _type: "headlineSection";
        _key: string;
        images: null;
        logo: null;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
        projectsPageLink: null;
      }
    | {
        images: Array<{
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          _key: string;
        }> | null;
        logo: {
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash?: string;
            extension?: string;
            mimeType?: string;
            size?: number;
            assetId?: string;
            uploadId?: string;
            path?: string;
            url?: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        _type: "heroSection";
        _key: string;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
        projectsPageLink: null;
        headline: null;
      }
    | {
        title?: string;
        pressSource?: boolean;
        _type: "pressCoverageSection";
        _key: string;
        images: null;
        logo: null;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
        projectsPageLink: null;
        headline: null;
      }
    | {
        title?: string;
        projectsPageLink: {
          _id: string;
          _type: "page";
          name: string | null;
          slug: Slug | null;
        } | null;
        projectLinkText?: string;
        viewAllLinkText?: string;
        selectedProjects: Array<{
          _id: string;
          _type: "project";
          name: string | null;
          slug: Slug | null;
          date: string | null;
          previewImages: Array<{
            asset: {
              _id: string;
              _type: "sanity.imageAsset";
              _createdAt: string;
              _updatedAt: string;
              _rev: string;
              originalFilename?: string;
              label?: string;
              title?: string;
              description?: string;
              altText?: string;
              sha1hash?: string;
              extension?: string;
              mimeType?: string;
              size?: number;
              assetId?: string;
              uploadId?: string;
              path?: string;
              url?: string;
              metadata?: SanityImageMetadata;
              source?: SanityAssetSourceData;
            } | null;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            isFeatured: boolean | null;
            showOnMobile: boolean | null;
            isFeaturedMobile: boolean | null;
            _type: "image";
            _key: string;
          }> | null;
        }> | null;
        _type: "projectsSection";
        _key: string;
        images: null;
        logo: null;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        headline: null;
      }
    | {
        title?: string;
        content?: Markdown;
        _type: "termsConditionsSection";
        _key: string;
        images: null;
        logo: null;
        backgroundImage: null;
        contactUsImage: null;
        mainImage: null;
        previewImages: null;
        gallery: null;
        selectedProjects: null;
        projectsPageLink: null;
        headline: null;
      }
  > | null;
} | null;

// Source: lib/queries/project.ts
// Variable: PROJECT_QUERY
// Query: *[  _type == "project"   && slug.current == $projectSlug][0]{  _id,  name,  slug,  date,  shortDescription,  projectSummary,  projectDescription,  mainImage{    ...,    alt,    asset->  },  previewImages[]{    ...,    asset->,    isFeatured,    showOnMobile,    isFeaturedMobile  },  gallery[]{    ...,    asset->  },  galleryLayout[]{    type,    images  }}
export type PROJECT_QUERYResult = {
  _id: string;
  name: string | null;
  slug: Slug | null;
  date: string | null;
  shortDescription: string | null;
  projectSummary: InternationalizedArrayString | null;
  projectDescription: InternationalizedArrayString | null;
  mainImage: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    alt: null;
  } | null;
  previewImages: Array<{
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    isFeatured: boolean | null;
    showOnMobile: boolean | null;
    isFeaturedMobile: boolean | null;
    _type: "image";
    _key: string;
  }> | null;
  gallery: Array<{
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  galleryLayout: Array<{
    type: string | null;
    images: Array<string> | null;
  }> | null;
} | null;
// Variable: SETTINGS_QUERY
// Query: *[_type == "settings"][0]{  contactUsButton{    text,    contactPages{      english->{slug},      french->{slug}    },    buttonStyle  },  relatedProjectsTitle,  viewAllLinkText}
export type SETTINGS_QUERYResult = {
  contactUsButton: {
    text: InternationalizedArrayString | null;
    contactPages: {
      english: {
        slug: Slug | null;
      } | null;
      french: {
        slug: Slug | null;
      } | null;
    } | null;
    buttonStyle: null;
  } | null;
  relatedProjectsTitle: InternationalizedArrayString | null;
  viewAllLinkText: InternationalizedArrayString | null;
} | null;
// Variable: RELATED_PROJECTS_QUERY
// Query: *[  _type == "project"   && _id != $currentProjectId  && defined(slug.current)]{  _id,  name,  slug,  date,  mainImage{    ...,    asset->  }} | order(_createdAt desc) [0...10]
export type RELATED_PROJECTS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  date: string | null;
  mainImage: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "footer"][0]{\n  logoDesktop {\n    asset->{\n      _id,\n      url,\n      metadata {\n        dimensions {\n          width,\n          height\n        }\n      }\n    },\n    alt\n  },\n  logoMobile {\n    asset->{\n      _id,\n      url,\n      metadata {\n        dimensions {\n          width,\n          height\n        }\n      }\n    },\n    alt\n  },\n  column1 {\n    showLanguageSwitch,\n    termsPageEN->{\n      name,\n      slug\n    },\n    termsPageFR->{\n      name,  \n      slug\n    }\n  },\n  "settingsContact": *[_type == "settings"][0].contactInfo {\n    headOfDesign {\n      name,\n      phone,\n      email\n    },\n    generalInquiries {\n      email\n    }\n  },\n  "settingsSocial": *[_type == "settings"][0].socialMedia[] {\n    platform,\n    url\n  },\n}': FOOTER_QUERYResult;
    '*[_type == "navbar"][0]{\n  navbarStructure {\n    brandText,\n    logo {\n      asset->{\n        _id,\n        url,\n        metadata {\n          dimensions {\n            width,\n            height\n          }\n        }\n      },\n      alt\n    },\n    logoWhite {\n      asset->{\n        _id,\n        url,\n        metadata {\n          dimensions {\n            width,\n            height\n          }\n        }\n      },\n      alt\n    },\n    menuItems {\n      menuItemsEN[] {\n        page-> {\n          name,\n          slug,\n          language\n        },\n        mobileImage {\n          asset->{\n            _id,\n            url,\n            metadata {\n              dimensions {\n                width,\n                height\n              }\n            }\n          },\n          alt\n        }\n      },\n      menuItemsFR[] {\n        page-> {\n          name,\n          slug,\n          language  \n        },\n        mobileImage {\n          asset->{\n            _id,\n            url,\n            metadata {\n              dimensions {\n                width,\n                height\n              }\n            }\n          },\n          alt\n        }\n      }\n    }\n  },\n  "settingsSocial": *[_type == "settings"][0].socialMedia[] {\n    platform,\n    url\n  },\n  "termsPageEN": *[_type == "page" && language == "en" && name match "*Terms*" || name match "*Conditions*"][0] {\n    name,\n    slug\n  },\n  "termsPageFR": *[_type == "page" && language == "fr" && name match "*Terms*" || name match "*Conditions*"][0] {\n    name,\n    slug\n  },\n  "settingsContact": *[_type == "settings"][0].contactInfo {\n    headOfDesign {\n      name,\n      phone,\n      email\n    },\n    generalInquiries {\n      email\n    }\n  }\n}': NAVBAR_QUERYResult;
    '*[_type == "project"] | order(date desc) {\n  _id,\n  name,\n  slug,\n  shortDescription,\n  date,\n  projectSummary,\n  projectDescription,\n  mainImage {\n    asset-> {\n      _id,\n      url,\n      metadata {\n        dimensions {\n          width,\n          height\n        }\n      }\n    },\n    alt,\n    hotspot,\n    crop\n  },\n  "previewImages": previewImages[]{\n    ..., \n    asset->,\n    isFeatured,\n    showOnMobile,\n    isFeaturedMobile\n  },\n  projectGallery[] {\n    asset-> {\n      _id,\n      url,\n      metadata {\n        dimensions {\n          width,\n          height\n        }\n      }\n    },\n    alt,\n    hotspot,\n    crop,\n    showInGrid,\n    gridSpan\n  }\n}': PROJECTS_QUERYResult;
    '*[\n  _type == "page" \n  && name == "Home" \n  && language == "fr"\n][0]{\n  ...,\n  components[]{\n    ...,\n    "images": images[]{..., asset->},\n    "logo": logo{..., asset->},\n    "backgroundImage": backgroundImage{..., asset->},\n    "contactUsImage": contactUsImage{..., asset->},\n    "mainImage": mainImage{..., asset->},\n    "previewImages": previewImages[]{..., asset->},\n    "gallery": gallery[]{..., asset->},\n    "selectedProjects": selectedProjects[]-> {\n      _id,\n      _type,\n      name,\n      slug,\n      date,\n      "previewImages": previewImages[]{\n        ..., \n        asset->,\n        isFeatured,\n        showOnMobile,\n        isFeaturedMobile\n      },\n    },\n    "projectsPageLink": projectsPageLink->{\n      _id,\n      _type,\n      name,\n      slug\n    },\n    headline[]{\n      ...,\n      markDefs[]{\n        ...,\n        "linkToPage": linkToPage->{\n          _id,\n          _type,\n          name,\n          slug\n        }\n      }\n    }\n  }\n}': HOME_QUERY_FRResult;
    '*[\n  _type == "page" \n  && name == "Home" \n  && language == "en"\n][0]{\n  ...,\n  components[]{\n    ...,\n    "images": images[]{..., asset->},\n    "logo": logo{..., asset->},\n    "backgroundImage": backgroundImage{..., asset->},\n    "contactUsImage": contactUsImage{..., asset->},\n    "mainImage": mainImage{..., asset->},\n    "previewImages": previewImages[]{..., asset->},\n    "gallery": gallery[]{..., asset->},\n    "selectedProjects": selectedProjects[]-> {\n      _id,\n      _type,\n      name,\n      slug,\n      date,\n      "previewImages": previewImages[]{\n        ..., \n        asset->,\n        isFeatured,\n        showOnMobile,\n        isFeaturedMobile\n      },\n    },\n    "projectsPageLink": projectsPageLink->{\n      _id,\n      _type,\n      name,\n      slug\n    },\n    headline[]{\n      ...,\n      markDefs[]{\n        ...,\n        "linkToPage": linkToPage->{\n          _id,\n          _type,\n          name,\n          slug\n        }\n      }\n    }\n  }\n}': HOME_QUERY_ENResult;
    '*[\n  _type == "page" \n  && slug.current == $slug \n  && language == "fr"\n][0]{\n  name,\n  language,\n  components[]{\n    ...,\n    "images": images[]{..., asset->},\n    "logo": logo{..., asset->},\n    "backgroundImage": backgroundImage{..., asset->},\n    "contactUsImage": contactUsImage{..., asset->},\n    "mainImage": mainImage{..., asset->},\n    "previewImages": previewImages[]{..., asset->},\n    "gallery": gallery[]{..., asset->},\n    "selectedProjects": selectedProjects[]-> {\n      _id,\n      _type,\n      name,\n      slug,\n      date,\n      "previewImages": previewImages[]{\n        ..., \n        asset->,\n        isFeatured,\n        showOnMobile,\n        isFeaturedMobile\n      },\n    },\n    "projectsPageLink": projectsPageLink->{\n      _id,\n      _type,\n      name,\n      slug\n    },\n    _type == "contentSection" => {\n      section3 {\n        ...,\n        "image": image{..., asset->},\n        "buttonLink": buttonLink->{\n          _id,\n          _type,\n          name,\n          slug\n        }\n      }\n    },\n    headline[]{\n      ...,\n      markDefs[]{\n        ...,\n        "linkToPage": linkToPage->{\n          _id,\n          _type,\n          name,\n          slug\n        }\n      }\n    }\n  }\n}': PAGE_QUERY_FRResult;
    '*[\n  _type == "page" \n  && slug.current == $slug \n  && language == "en"\n][0]{\n  name,\n  language,\n  components[]{\n    ...,\n    "images": images[]{..., asset->},\n    "logo": logo{..., asset->},\n    "backgroundImage": backgroundImage{..., asset->},\n    "contactUsImage": contactUsImage{..., asset->},\n    "mainImage": mainImage{..., asset->},\n    "previewImages": previewImages[]{..., asset->},\n    "gallery": gallery[]{..., asset->},\n    "selectedProjects": selectedProjects[]-> {\n      _id,\n      _type,\n      name,\n      slug,\n      date,\n      "previewImages": previewImages[]{\n        ..., \n        asset->,\n        isFeatured,\n        showOnMobile,\n        isFeaturedMobile\n      },\n    },\n    "projectsPageLink": projectsPageLink->{\n      _id,\n      _type,\n      name,\n      slug\n    },\n    _type == "contentSection" => {\n      section3 {\n        ...,\n        "image": image{..., asset->},\n        "buttonLink": buttonLink->{\n          _id,\n          _type,\n          name,\n          slug\n        }\n      }\n    },\n    headline[]{\n      ...,\n      markDefs[]{\n        ...,\n        "linkToPage": linkToPage->{\n          _id,\n          _type,\n          name,\n          slug\n        }\n      }\n    }\n  }\n}': PAGE_QUERY_ENResult;
    '*[\n  _type == "project" \n  && slug.current == $projectSlug\n][0]{\n  _id,\n  name,\n  slug,\n  date,\n  shortDescription,\n  projectSummary,\n  projectDescription,\n  mainImage{\n    ...,\n    alt,\n    asset->\n  },\n  previewImages[]{\n    ...,\n    asset->,\n    isFeatured,\n    showOnMobile,\n    isFeaturedMobile\n  },\n  gallery[]{\n    ...,\n    asset->\n  },\n  galleryLayout[]{\n    type,\n    images\n  }\n}': PROJECT_QUERYResult;
    '*[_type == "settings"][0]{\n  contactUsButton{\n    text,\n    contactPages{\n      english->{slug},\n      french->{slug}\n    },\n    buttonStyle\n  },\n  relatedProjectsTitle,\n  viewAllLinkText\n}': SETTINGS_QUERYResult;
    '*[\n  _type == "project" \n  && _id != $currentProjectId\n  && defined(slug.current)\n]{\n  _id,\n  name,\n  slug,\n  date,\n  mainImage{\n    ...,\n    asset->\n  }\n} | order(_createdAt desc) [0...10]': RELATED_PROJECTS_QUERYResult;
  }
}
